// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Json")>]
[<assembly: AssemblyProductAttribute("FSharp.Json")>]
[<assembly: AssemblyDescriptionAttribute("Elm inspired Json encoder/decoder combinator library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Json"
    let [<Literal>] AssemblyProduct = "FSharp.Json"
    let [<Literal>] AssemblyDescription = "Elm inspired Json encoder/decoder combinator library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
